
orb_slam2_mono_node:
  ros__parameters:

    publish_pointcloud: true
    publish_pose: true
    localize_only: false
    reset_map: false

    # static parameters
    load_map: false
    map_file: map.bin
   

    pointcloud_frame_id: map
    camera_frame_id: camera_link
    min_num_kf_in_map: 5

    #ORB parameters
    ORBextractor/nFeatures: 1200
    ORBextractor/scaleFactor: 1.2
    ORBextractor/nLevels: 8
    ORBextractor/iniThFAST: 20
    ORBextractor/minThFAST: 7

    #Camera Parameters
    #Camera frames per second
    camera_fps: 30
    #Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale) 
    camera_rgb_encoding: false

    #Camera calibration parameters
    #If the node should wait for a camera_info topic to take the camera calibration data
    load_calibration_from_cam: true
    #Camera calibration and distortion parameters (OpenCV). Only needed if your not using the camera_info topic to read them. 
    #camera_fx: 284.6852111816406
    #camera_fy: 626.8605346679688
    #camera_cx: 311.43603515625
    #camera_cy: 248.0950164794922
    #Camera calibration and distortion parameters (OpenCV) 
    #camera_k1: -0.09097914397716522
    #camera_k2: 0.06503549218177795
    #camera_p1: 0.000849052332341671
    #camera_p2: 0.001785792293958366
    #IR projector baseline times fx (aprox.)
    #camera_baseline: 30.464328718